# -*- coding: utf-8 -*-
"""Contenu des Sheets de travail Eoleaf - cannibalisation, H1, images."""
FICHIERS = {}

FICHIERS["Cannibalisation clusters FR Eoleaf"] = (
 "Important ⚠️ : quand deux pages visent la même intention, Google en choisit une et dilue les deux. "
 "L'onglet sémantique en porte la preuve : « purificateur d'air voiture » y est planifié sur 3 URL "
 "différentes, « purificateur d'air chambre » sur 2, « purificateur d'air allergie chat » sur 2, "
 "« aspirateur de fumée de cigarette » sur 2. Un pilier par cluster, le reste fusionne ou redirige.",
 ["CLUSTER","REQUETE PRINCIPALE","VOLUME","URL","POSITION CONNUE","ROLE PROPOSE","DECISION","STATUT"],
 [
  ["Voiture","purificateur d'air voiture","210","/fr/collections/purificateur-air-voiture-pure-car","non relevée","Catégorie : reste la porte d'entrée commerciale","Conserver",'A FAIRE'],
  ["Voiture","purificateur d'air voiture","210","/fr/products/purificateur-air-purcar","20","Fiche produit : unité d'achat","Conserver",'A FAIRE'],
  ["Voiture","purificateur d'air voiture","210","/fr/pages/acheter-un-purificateur-dair-pour-la-voiture","5","PILIER de cluster","Conserver et lier vers la fiche PurCar",'A FAIRE'],
  ["Voiture","purificateur d'air voiture","210","/fr/pages/installer-un-purificateur-dair-dans-votre-voiture","16","Doublon d'intention","Fusionner dans le pilier puis 301",'A FAIRE'],
  ["Chambre et sommeil","purificateur d air chambre","170","/fr/pages/acheter-un-purificateur-dair-pour-votre-chambre","7","PILIER de cluster","Conserver",'A FAIRE'],
  ["Chambre et sommeil","purificateur d'air chambre","170","/fr/pages/dormez-mieux-en-installant-un-purificateur-dair-dans-votre-chambre","7","Doublon d'intention","Fusionner dans le pilier puis 301",'A FAIRE'],
  ["Chambre et sommeil","purificateur d'air pour dormir","non relevé","/fr/pages/acheter-un-purificateur-dair-pour-dormir","non relevée","Doublon d'intention","Fusionner dans le pilier puis 301",'A FAIRE'],
  ["Allergies animaux","purificateur d'air allergie chat","140","/fr/pages/acheter-un-purificateur-dair-pour-les-allergies-aux-animaux-de-compagnie","13","PILIER de cluster","Conserver",'A FAIRE'],
  ["Allergies animaux","purificateur d'air allergie chat","140","/fr/pages/comment-un-purificateur-dair-peut-aider-avec-les-allergies-aux-animaux","19","Doublon d'intention","Fusionner dans le pilier puis 301",'A FAIRE'],
  ["Allergies animaux","purificateur d'air animaux","110","/fr/pages/comment-eliminer-les-odeurs-danimaux-de-votre-maison","5","Question satellite : conserver","Conserver et lier vers le pilier",'A FAIRE'],
  ["Allergies animaux","URL cassée","non applicable","/fr/pages/acheter-un-purificateur-dair-pour-les-allergies-aux-animaux-de-compagnie=","non applicable","Signe égal parasite dans un lien interne","Corriger le lien source puis 301",'A FAIRE'],
  ["Fumée de tabac","aspirateur fumée cigarette","390","/fr/pages/acheter-un-purificateur-dair-pour-la-fumee-de-cigarettes","5","PILIER de cluster","Conserver",'A FAIRE'],
  ["Fumée de tabac","aspirateur de fumée de cigarette","260","/fr/pages/acheter-un-purificateur-dair-contre-la-fumee-de-cigare","20","Doublon d'intention","Fusionner dans le pilier puis 301",'A FAIRE'],
  ["Fumée de tabac","fumée cigare","non relevé","/fr/pages/acheter-un-purificateur-dair-pour-la-fumee-de-cigare","non relevée","Doublon du doublon : deux slugs pour le cigare","Fusionner dans le pilier puis 301",'A FAIRE'],
  ["Fumée de tabac","protéger ses poumons","non relevé","/fr/pages/utiliser-un-purificateur-dair-pour-proteger-vos-poumons-de-la-fumee-de-cigarette","non relevée","Doublon d'intention","Fusionner dans le pilier puis 301",'A FAIRE'],
  ["Fumée de tabac","fumée cigarette","260","/fr/pages/comment-le-tabagisme-contribue-a-la-pollution-de-lair","6","Question satellite : conserver","Conserver et lier vers le pilier",'A FAIRE'],
  ["Dentaire","purificateur d'air dentiste","non relevé","/fr/pages/acheter-un-purificateur-dair-pour-les-cabinets-dentaires","non relevée","PILIER de cluster","Conserver",'A FAIRE'],
  ["Dentaire","purificateur d'air dentiste","non relevé","/fr/pages/acheter-un-purificateur-dair-pour-les-dentistes-purificateurs-dair-dentaires","non relevée","Doublon d'intention","Fusionner dans le pilier puis 301",'A FAIRE'],
  ["Dentaire","purificateur d'air dentiste","non relevé","/fr/pages/acheter-un-purificateur-dair-pour-cabinets-de-dentistes-assainisseurs-dair-dentaires","non relevée","Troisième page sur la même intention","Fusionner dans le pilier puis 301",'A FAIRE'],
  ["Salon de coiffure","purificateur d'air salon de coiffure","non relevé","/fr/pages/acheter-un-purificateur-dair-pour-salon-de-coiffure","non relevée","PILIER de cluster","Conserver",'A FAIRE'],
  ["Salon de coiffure","purificateur d'air salon de coiffure","non relevé","/fr/pages/acheter-un-purificateur-dair-pour-les-salons-de-coiffure","non relevée","Doublon au pluriel","Fusionner dans le pilier puis 301",'A FAIRE'],
  ["Poussière et acariens","purificateur d'air poussière","590","/fr/pages/acheter-un-purificateur-dair-pour-la-poussiere","10","PILIER de cluster","Conserver",'A FAIRE'],
  ["Poussière et acariens","purificateur d'air acariens","non relevé","/fr/pages/acheter-un-purificateur-dair-pour-les-acariens","non relevée","Doublon d'intention","Fusionner dans le pilier puis 301",'A FAIRE'],
  ["Poussière et acariens","acariens de poussière","170","/fr/pages/comment-utiliser-les-purificateurs-dair-pour-lutter-contre-les-allergies-a-la-poussiere-e-aux-acariens","19","Question satellite : conserver mais slug fautif (« e-aux »)","Conserver, corriger le slug avec 301",'A FAIRE'],
  ["Professionnel et industriel","purificateur d'air professionnel","590","/fr/collections/purificateurs-air","4","Catégorie : porte d'entrée commerciale","Conserver",'A FAIRE'],
  ["Professionnel et industriel","purificateur professionnel","210","/fr/pages/acheter-un-purificateur-dair-professionnel","4","PILIER éditorial du cluster","Conserver et lier vers la catégorie",'A FAIRE'],
  ["Professionnel et industriel","purificateur d'air industriel","260","/fr/pages/acheter-un-purificateur-dair-industriel","12","Intention distincte : conserver","Conserver et lier vers le pilier",'A FAIRE'],
  ["Professionnel et industriel","grand espace","non relevé","/fr/pages/acheter-un-purificateur-dair-commercial-pour-un-grand-espace","non relevée","Doublon d'intention avec industriel","Fusionner puis 301",'A FAIRE'],
  ["Professionnel et industriel","professionnels","non relevé","/fr/pages/professionnels","non relevée","Page institutionnelle B2B : rôle à clarifier","Conserver, H1 à poser, lier vers le pilier",'A FAIRE'],
  ["HEPA","purificateur d'air hepa","880","/fr/pages/acheter-un-purificateur-dair-hepa","5","PILIER commercial du cluster","Conserver",'A FAIRE'],
  ["HEPA","filtre hepa","2900","/fr/pages/comment-fonctionnent-les-filtres-hepa","6","Question pilier : conserver","Conserver et lier vers le pilier commercial",'A FAIRE'],
  ["HEPA","purificateur d air hepa","880","/fr/","19","L'accueil est planifié sur la même requête que le pilier","Retirer cette cible de l'accueil : elle appartient au pilier",'A FAIRE'],
  ["Charbon actif","purificateur d'air charbon actif","170","/fr/pages/acheter-un-purificateur-dair-au-charbon","4","PILIER commercial du cluster","Conserver",'A FAIRE'],
  ["Charbon actif","filtration par charbon actif","110","/fr/pages/quest-ce-que-la-filtration-au-charbon-actif","15","Question pilier : conserver","Conserver et lier vers le pilier",'A FAIRE'],
  ["Charbon actif","charbon actif filtration air","non relevé","/fr/pages/le-charbon-actif-et-son-role-dans-la-filtration-de-lair","non relevée","Doublon de la question pilier","Fusionner puis 301",'A FAIRE'],
  ["Ozone","générateur d'ozone","480","/fr/pages/purificateurs-dair-a-lozone-et-generateurs-dozone-ce-quil-faut-savoir","4","PILIER de cluster","Conserver",'A FAIRE'],
  ["Ozone","générateur d'ozone","480","/fr/pages/purificateurs-et-generateurs-a-lozone-ce-quil-faut-savoir","non relevée","Doublon quasi identique : deux slugs, un sujet","Fusionner puis 301",'A FAIRE'],
  ["Ionisation","ionisation de l'air","480","/fr/pages/tout-savoir-sur-lionisation","8","PILIER de cluster","Conserver",'A FAIRE'],
  ["Ionisation","ioniseur d'air","1900","/fr/pages/ioniseurs-a-quoi-servent-ils","8","Intention distincte : conserver","Conserver et lier vers le pilier",'A FAIRE'],
  ["Ionisation","ion s","260","/fr/pages/les-ions-negatifs-et-leurs-bienfaits-pour-notre-sante","11","Question satellite : conserver","Conserver et lier vers le pilier",'A FAIRE'],
  ["Choix du purificateur","meilleur purificateur air","320","/fr/pages/choisir-le-meilleur-purificateur-dair-pour-100-m2","5","Intention surface : conserver","Conserver",'A FAIRE'],
  ["Choix du purificateur","comment choisir un purificateur d'air","non relevé","/fr/pages/guide-dachat-comment-choisir-un-purificateur-dair","non relevée","PILIER de cluster : le guide d'achat","Conserver",'A FAIRE'],
  ["Choix du purificateur","comment choisir le meilleur purificateur","non relevé","/fr/pages/comment-choisir-le-meilleur-purificateur-dair","non relevée","Doublon du guide d'achat","Fusionner dans le guide puis 301",'A FAIRE'],
  ["Choix du purificateur","plus grand est-il meilleur","non relevé","/fr/pages/un-purificateur-dair-plus-grand-est-il-forcement-meilleur","non relevée","Question satellite : conserver","Conserver et lier vers le guide",'A FAIRE'],
  ["Vapotage","purificateur d'air vapotage","non relevé","/fr/pages/acheter-un-purificateur-dair-contre-le-vapotage","non relevée","PILIER de cluster","Conserver",'A FAIRE'],
  ["Vapotage","risques du vapotage passif","non relevé","/fr/pages/les-risques-du-vapotage-et-du-vapotage-passif","non relevée","Question satellite : conserver","Conserver et lier vers le pilier",'A FAIRE'],
  ["","","","","","","",""],
  ["REGLE APPLIQUEE","Une page en top 3 ne se touche pas : à vérifier au contrôle GSC du ticket 01 avant toute fusion","","","","","",""],
  ["","Une fusion se fait dans ce sens : le contenu utile remonte dans le pilier, PUIS la 301 est posée","","","","","",""],
 ])

FICHIERS["H1 manquants Eoleaf"] = (
 "Important ⚠️ : le H1 dit à Google et au visiteur de quoi parle la page. L'extraction balisage compte "
 "18 H1 manquants et 12 trop longs. Les manquants se concentrent sur 5 gabarits Shopify : une correction "
 "de gabarit traite la page dans les 12 langues d'un seul geste. Cible : un H1 unique, 20 à 70 "
 "caractères, contenant l'expression cible.",
 ["URL","GABARIT","H1 ACTUEL","PROBLEME","REQUETE CIBLE","H1 PROPOSE","LONGUEUR","STATUT"],
 [
  ["/fr/collections/filtres-et-accessoires","Collection","","Manquant","filtre purificateur d'air eoleaf","Filtres et accessoires pour purificateurs d'air Eoleaf","54",'A FAIRE'],
  ["/fr/collections/all","Collection","","Manquant","purificateur d'air eoleaf","Tous les purificateurs d'air et accessoires Eoleaf","50",'A FAIRE'],
  ["/fr/collections","Collection","Collections","Trop court","gamme purificateur d'air","Nos gammes de purificateurs d'air professionnels","48",'A FAIRE'],
  ["/fr/pages/professionnels","Page métier","","Manquant","purificateur d'air entreprise","Purificateurs d'air pour les professionnels","43",'A FAIRE'],
  ["/fr/pages/comparatif-produit","Comparatif","","Manquant","comparatif purificateur d'air eoleaf","Comparatif des purificateurs d'air Eoleaf","41",'A FAIRE'],
  ["/fr/pages/certifications-eoleaf","Institutionnel","","Manquant","certification purificateur d'air","Certifications de nos purificateurs d'air","42",'A FAIRE'],
  ["/fr/pages/a-propos-de-nous","Institutionnel","","Manquant","eoleaf entreprise","Eoleaf, expert français du purificateur d'air","46",'A FAIRE'],
  ["/fr/pages/devenez-distributeur","Institutionnel","","Manquant","devenir distributeur purificateur d'air","Devenir distributeur de purificateurs d'air","44",'A FAIRE'],
  ["/fr/pages/faqs","FAQ","","Manquant","question purificateur d'air","Questions fréquentes sur les purificateurs d'air","49",'A FAIRE'],
  ["/fr/pages/formulaire-sav","Service","Formulaire SAV","Trop court","sav purificateur d'air eoleaf","Service après-vente : votre demande d'assistance","49",'A FAIRE'],
  ["/fr/cart","Panier","Votre panier","Trop court","non applicable","À laisser tel quel : page transactionnelle non indexable","","SANS OBJET"],
  ["/fr","Accueil","Purificateurs d'air haute performance, de qualité médicale, certifiés HEPA","Trop long (74)","purificateur d'air haut de gamme","Purificateurs d'air haut de gamme certifiés HEPA","48",'A FAIRE'],
  ["/fr/products/purificateur-air-purcar","Fiche produit","Purificateur d'air PurCar Filtre HEPA H13 & Ioniseur - Pour tout véhicule","Trop long (73)","purificateur voiture eoleaf","Purificateur d'air PurCar pour voiture, filtre HEPA H13","55",'A FAIRE'],
  ["/fr/products/filtre-de-rechange-neopur-400","Fiche produit","Filtre de rechange Eoleaf NeoPur 400 (compatible avec AIRVIA ORIGIN 40 et Eoleaf AEROPRO40)","Trop long (91)","filtre neopur 400","Filtre de rechange NeoPur 400","30",'A FAIRE'],
  ["/fr/products/filtre-de-rechange-altapur-700","Fiche produit","Filtre de rechange AltaPur 700 (compatible avec AIRVIA PRO 150 et Eoleaf AEROPRO150)","Trop long (84)","filtre altapur 700","Filtre de rechange AltaPur 700","31",'A FAIRE'],
  ["/fr/products/prefiltre-de-rechange-altapur-700","Fiche produit","Préfiltre de rechange AltaPur 700 (compatible avec AIRVIA PRO 150 et Eoleaf AEROPRO150)","Trop long (87)","préfiltre altapur 700","Préfiltre de rechange AltaPur 700","34",'A FAIRE'],
  ["/fr/products/lampe-uvc-rechange","Fiche produit","Lampe UV de rechange Eoleaf (compatible avec AIRVIA AERO 100, PRO 150 et ORIGIN 40)","Trop long (83)","lampe uvc purificateur","Lampe UVC de rechange Eoleaf","29",'A FAIRE'],
  ["/fr/products/purificateur-air-neopur-400","Fiche produit","Purificateur d'air NeoPur 400 Surface 40 m2 - Intelligent & Connecté","Conforme (68) mais « m2 » à écrire « m² »","Eoleaf Neopur 400","Purificateur d'air NeoPur 400, jusqu'à 40 m²","44",'A FAIRE'],
  ["","","","","","","",""],
  ["MENTION DE COMPATIBILITE","Les mentions « compatible avec AIRVIA … » sortent du H1 et descendent dans le corps de la fiche : elles allongent le H1 sans porter la requête","","","","","",""],
  ["REGLE APPLIQUEE","Aucune page en top 3 n'est modifiée : à vérifier au contrôle GSC du ticket 01","","","","","",""],
 ])

FICHIERS["Images a corriger Eoleaf"] = (
 "Important ⚠️ : 334 images pour 91,3 Mo relevées, soit 273 Ko de moyenne. 64 images au-delà de 200 Ko, "
 "36 au-delà de 500 Ko, 99 PNG et aucun webp. Et 192 ALT vides sur 334, soit 57 %. Les plus lourdes sont "
 "des visuels de fiche produit, donc sur le gabarit qui encaisse. Cible : webp, moins de 200 Ko, largeur "
 "servie inférieure ou égale à 1500 px, un ALT descriptif partout.",
 ["FICHIER","GABARIT","POIDS ACTUEL Ko","FORMAT","LARGEUR SERVIE","POIDS CIBLE Ko","ALT PROPOSE","STATUT"],
 [
  ["PurCar_6.png","Fiche produit PurCar","3580","PNG","2048","moins de 150","Purificateur d'air PurCar installé dans un habitacle de voiture","A FAIRE"],
  ["PurCar_5.png","Fiche produit PurCar","3490","PNG","2048","moins de 150","Purificateur d'air PurCar vu de trois quarts","A FAIRE"],
  ["NeoPur_pro_2.png","Fiche produit NeoPur 400","3477","PNG","1900","moins de 150","Purificateur d'air NeoPur 400 en bureau professionnel","A FAIRE"],
  ["PurCar_1.png","Fiche produit PurCar","3380","PNG","2048","moins de 150","Purificateur d'air PurCar de face","A FAIRE"],
  ["PurCar_3.png","Fiche produit PurCar","3377","PNG","2048","moins de 150","Filtre HEPA H13 du purificateur PurCar","A FAIRE"],
  ["PurCar_2.png","Fiche produit PurCar","3250","PNG","2048","moins de 150","Purificateur d'air PurCar fixé sur appuie-tête","A FAIRE"],
  ["PurCar_4.png","Fiche produit PurCar","3028","PNG","2048","moins de 150","Commandes du purificateur d'air PurCar","A FAIRE"],
  ["TeraPur_home_3.png","Fiche produit TeraPur 600","2958","PNG","2048","moins de 150","Purificateur d'air TeraPur 600 dans un salon","A FAIRE"],
  ["fr_qualite_d_air_1680175736.png","Accueil","2929","PNG","non relevée","moins de 150","Indice de qualité de l'air intérieur mesuré par Eoleaf","A FAIRE"],
  ["TeraPur_home_5.png","Fiche produit TeraPur 600","2796","PNG","2048","moins de 150","Purificateur d'air TeraPur 600 vu de côté","A FAIRE"],
  ["TeraPur_pro_1.png","Fiche produit TeraPur 600","2792","PNG","2048","moins de 150","Purificateur d'air TeraPur 600 en salle de réunion","A FAIRE"],
  ["NeoPur_pro_4.png","Fiche produit NeoPur 400","2679","PNG","2048","moins de 150","Écran de contrôle du purificateur NeoPur 400","A FAIRE"],
  ["AEROPRO100-ENV1.jpg","Fiche produit (ancien modèle)","non relevé","JPEG","800","moins de 150","Purificateur d'air TeraPur 600 en cabinet médical","A FAIRE"],
  ["150-04.jpg","Fiche produit AltaPur 700","non relevé","JPEG","1500","moins de 150","Purificateur d'air AltaPur 700 en grand espace","A FAIRE"],
  ["AEROPRO40-ENV5.jpg","Fiche produit (ancien modèle)","non relevé","JPEG","750","moins de 150","Purificateur d'air NeoPur 400 dans une chambre","A FAIRE"],
  ["AEROPRO150-ENV1.jpg","Fiche produit (ancien modèle)","non relevé","JPEG","2000","moins de 150","Purificateur d'air AltaPur 700 en open space","A FAIRE"],
  ["AEROPRO40-ENV4.jpg","Fiche produit (ancien modèle)","non relevé","JPEG","750","moins de 150","Purificateur d'air NeoPur 400 posé au sol","A FAIRE"],
  ["AEROPRO150-ENV2.jpg","Fiche produit (ancien modèle)","non relevé","JPEG","2000","moins de 150","Purificateur d'air AltaPur 700 en salle d'attente","A FAIRE"],
  ["EOLEAF_Website_Splash_Photo_PURIFIERS_FILTERS_v2_12x9.jpg","Collection filtres","non relevé","JPEG","non relevée","moins de 150","Gamme de filtres de rechange Eoleaf","A FAIRE"],
  ["Car_1.jpg","Fiche produit PurCar","non relevé","JPEG","3000","moins de 150","Purificateur d'air PurCar dans une voiture","A FAIRE"],
  ["","","","","","","",""],
  ["SYNTHESE","VALEUR RELEVEE","CIBLE","","","","",""],
  ["Images relevées","334","non applicable","","","","",""],
  ["Poids total","91,3 Mo","moins de 25 Mo","","","","",""],
  ["Images au-delà de 200 Ko","64","0","","","","",""],
  ["Images au-delà de 500 Ko","36","0","","","","",""],
  ["Fichiers PNG","99","0 sur les gabarits d'achat","","","","",""],
  ["Fichiers webp","0","tous les gabarits d'achat","","","","",""],
  ["ALT vides","192 sur 334","0 sur accueil, collection et fiche produit","","","","",""],
  ["","","","","","","",""],
  ["METHODE","Les 172 ALT vides restants se traitent dans la médiathèque Shopify, une fois par fichier : l'ALT suit l'image dans les 12 langues","","","","","",""],
 ])
